# Generated by Django 2.2.2 on 2019-07-10 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_remove_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userid',
        ),
        migrations.AddField(
            model_name='post',
            name='postlikes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
