# Generated by Django 2.2.2 on 2019-07-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190710_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userid',
        ),
    ]
