# Generated by Django 2.2.2 on 2019-07-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_likescomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='likescomments',
        ),
    ]
