# Generated by Django 2.2.2 on 2019-07-11 10:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20190711_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None), blank=True, default=list, size=None),
        ),
    ]
